@Sphera_API_HostAddress = http://localhost:5000
@json = application/json
@uuid = 11111111-1111-1111-1111-111111111111

###
# SERVICES
# --------------------------------------------

# GetServices
GET {{Sphera_API_HostAddress}}/api/v1/Services
Accept: {{json}}

###

# CreateService
POST {{Sphera_API_HostAddress}}/api/v1/Services
Accept: {{json}}
Content-Type: {{json}}

{
  // coloque o payload do serviço aqui
}

###

# GetServiceById
GET {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}
Accept: {{json}}

###

# UpdateService
PUT {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}
Accept: {{json}}
Content-Type: {{json}}

{
  // payload para atualizar serviço
}

###

# DeleteService
DELETE {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}
Accept: {{json}}

###

# ActivateService
PATCH {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}/activate
Accept: {{json}}

###

# DeactivateService
PATCH {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}/deactivate
Accept: {{json}}





###
# PARTNERS
# --------------------------------------------

# GetPartners
GET {{Sphera_API_HostAddress}}/api/v1/Partners
Accept: {{json}}

###

# CreatePartner
POST {{Sphera_API_HostAddress}}/api/v1/Partners
Accept: {{json}}
Content-Type: {{json}}

{
  // payload do parceiro
}

###

# GetPartnerById
GET {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}
Accept: {{json}}

###

# UpdatePartner
PUT {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}
Accept: {{json}}
Content-Type: {{json}}

{
  // payload de atualização do parceiro
}

###

# DeletePartner
DELETE {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}
Accept: {{json}}

###

# ActivatePartner
PATCH {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}/activate
Accept: {{json}}

###

# DeactivatePartner
PATCH {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}/deactivate
Accept: {{json}}

###
# DOCUMENTS
# --------------------------------------------

# GetDocuments
GET {{Sphera_API_HostAddress}}/api/v1/Documents
Accept: {{json}}

###

# CreateDocument
POST {{Sphera_API_HostAddress}}/api/v1/Documents
Accept: {{json}}
Content-Type: {{json}}

{
  // payload de criação do documento
}

###

# DeleteDocument (em lote, conforme rota sem {id})
DELETE {{Sphera_API_HostAddress}}/api/v1/Documents
Accept: {{json}}

###

# GetDocumentById
GET {{Sphera_API_HostAddress}}/api/v1/Documents/{{uuid}}
Accept: {{json}}

###

# UpdateDocument
PUT {{Sphera_API_HostAddress}}/api/v1/Documents/{{uuid}}
Accept: {{json}}
Content-Type: {{json}}

{
  // payload de atualização do documento
}

###

# UploadDocument (forma genérica; ajuste se a API aceitar multipart)
POST {{Sphera_API_HostAddress}}/api/v1/Documents/{{uuid}}/upload
Accept: {{json}}
Content-Type: {{json}}

{
  "contentBase64": "<arquivo_em_base64>",
  "fileName": "documento.pdf",
  "contentType": "application/pdf"
}

###

# GetDocumentStatuses
GET {{Sphera_API_HostAddress}}/api/v1/Documents/statuses
Accept: {{json}}





###
# CLIENTS
# --------------------------------------------

# GetClients (todos)
GET {{Sphera_API_HostAddress}}/api/v1/Clients
Accept: {{json}}

###

# GetClients (com filtros na query)
GET {{Sphera_API_HostAddress}}/api/v1/Clients?PartnerId={{uuid}}&Status=true&Cnpj=12345678901234&Search=texto&IncludePartner=true
Accept: {{json}}

###

# CreateClient
POST {{Sphera_API_HostAddress}}/api/v1/Clients
Accept: {{json}}
Content-Type: {{json}}

{
  "partnerId": "{{uuid}}",
  "tradeName": "Acme LTDA",
  "legalName": "Acme Indústria e Comércio LTDA",
  "cnpj": "12345678000190",
  "stateRegistration": "ISENTO",
  "municipalRegistration": "123456",
  "address": {
    "street": "Rua Exemplo",
    "number": 123,
    "city": "São Paulo",
    "state": "SP",
    "zipCode": "01000-000"
  },
  "financialEmail": "financeiro@acme.com",
  "financialPhone": "+55 11 99999-0000",
  "email": "contato@acme.com",
  "phone": "+55 11 98888-0000",
  "billingDueDay": 15
}

###

# GetClientById (includePartner opcional)
GET {{Sphera_API_HostAddress}}/api/v1/Clients/{{uuid}}?includePartner=false
Accept: {{json}}

###

# UpdateClient
PUT {{Sphera_API_HostAddress}}/api/v1/Clients/{{uuid}}
Accept: {{json}}
Content-Type: {{json}}

{
  "id": "{{uuid}}",
  "tradeName": "Acme LTDA (Atualizada)",
  "legalName": "Acme Indústria e Comércio LTDA",
  "cnpj": "12345678000190",
  "stateRegistration": "ISENTO",
  "municipalRegistration": "123456",
  "address": {
    "street": "Rua Nova",
    "number": 456,
    "city": "São Paulo",
    "state": "SP",
    "zipCode": "01000-000"
  },
  "financialEmail": "financeiro@acme.com",
  "financialPhone": "+55 11 99999-0000",
  "email": "contato@acme.com",
  "phone": "+55 11 98888-0000",
  "billingDueDay": 20,
  "status": true
}

###

# DeleteClient
DELETE {{Sphera_API_HostAddress}}/api/v1/Clients/{{uuid}}
Accept: {{json}}

###

# ActivateClient
PATCH {{Sphera_API_HostAddress}}/api/v1/Clients/{{uuid}}/activate
Accept: {{json}}

###

# DeactivateClient
PATCH {{Sphera_API_HostAddress}}/api/v1/Clients/{{uuid}}/deactivate
Accept: {{json}}

###
# User
# --------------------------------------------
# GetUsers
GET {{Sphera_API_HostAddress}}/api/v1/Users
Accept: {{json}}
###

# CreateUser
POST {{Sphera_API_HostAddress}}/api/v1/Users
Accept: {{json}}
Content-Type: {{json}}

{
    "name": "Abner Oliveira",
    "email": "abnersanto2014@gmail.com",
    "roleId": 1
}

###
# UpdateUser
PUT {{Sphera_API_HostAddress}}/api/v1/Users/{{uuid}}
Accept: {{json}}
Content-Type: {{json}}

{
  "name": "Abner S. Oliveira",
  "roleId": 2
}


###
# Roles
# --------------------------------------------
# GetRoles
GET {{Sphera_API_HostAddress}}/api/v1/Roles
Accept: {{json}}

###
# GetRoles (com filtros)
GET {{Sphera_API_HostAddress}}/api/v1/Roles?Page=1&PageSize=10
Accept: {{json}}
