@Sphera_API_HostAddress = http://localhost:5000
@json = application/json
@uuid = d13a6fc6-0336-40e1-8116-bd4dfcbbe5a6
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbHMiOiJhYm5lcnNhbnRvMjAxNEBnbWFpbC5jb20iLCJuYW1lIjoiQWJuZXIgT2xpdmVpcmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA5LzA5L2lkZW50aXR5L2NsYWltcy9hY3RvciI6ImRjZTc4ODgzLTRmOTEtNDI2NS1hNDdkLWYxNDljY2FkOTI2YyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3NjQyMDEyODksImlzcyI6IlNwaGVyYS5BUEkiLCJhdWQiOiJTcGhlcmFBcHAifQ.fhNmJyPxstYvtcxg3MpffOrgTQi3XYD8FiBZBOYxSzU

###
# PARTNERS
# --------------------------------------------

# GetPartners
GET {{Sphera_API_HostAddress}}/api/v1/Partners
Accept: {{json}}
Authorization: {{token}}

###

# CreatePartner
POST {{Sphera_API_HostAddress}}/api/v1/Partners
Accept: {{json}}
Content-Type: {{json}}
Authorization: {{token}}

{
  "legalName": "Alcance Assessoria Empresarial"
}

###

# GetPartnerById
GET {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}
Accept: {{json}}
Authorization: {{token}}

###

# UpdatePartner
PUT {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}
Accept: {{json}}
Content-Type: {{json}}
Authorization: {{token}}

{
  // payload de atualização do parceiro
}

###

# DeletePartner
DELETE {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}
Accept: {{json}}
Authorization: {{token}}

###

# ActivatePartner
PATCH {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}/activate
Accept: {{json}}
Authorization: {{token}}

###

# DeactivatePartner
PATCH {{Sphera_API_HostAddress}}/api/v1/Partners/{{uuid}}/deactivate
Accept: {{json}}
Authorization: {{token}}
