@Sphera_API_HostAddress = http://localhost:5000
@json = application/json
@uuid = 11111111-1111-1111-1111-111111111111
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbHMiOiJhYm5lcnNhbnRvMjAxNEBnbWFpbC5jb20iLCJuYW1lIjoiQWJuZXIgT2xpdmVpcmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA5LzA5L2lkZW50aXR5L2NsYWltcy9hY3RvciI6ImRjZTc4ODgzLTRmOTEtNDI2NS1hNDdkLWYxNDljY2FkOTI2YyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3NjI3MzI5MTQsImlzcyI6IlNwaGVyYS5BUEkiLCJhdWQiOiJTcGhlcmFBcHAifQ.05VtoUEunBdrtMHyn_40wntT42rHANbgIIPNKK_9c2E

###
# SERVICES
# --------------------------------------------

# GetServices
GET {{Sphera_API_HostAddress}}/api/v1/Services
Accept: {{json}}
Authorization: {{token}}

###

# CreateService
POST {{Sphera_API_HostAddress}}/api/v1/Services
Accept: {{json}}
Content-Type: {{json}}
Authorization: {{token}}

{
  "name": "Pgr",
  "code": "pgr",
  "defaultDueInDays": 365
}

###

# GetServiceById
GET {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}
Accept: {{json}}
Authorization: {{token}}

###

# UpdateService
PUT {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}
Accept: {{json}}
Content-Type: {{json}}
Authorization: {{token}}

{
  // payload para atualizar serviço
}

###

# DeleteService
DELETE {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}
Accept: {{json}}
Authorization: {{token}}

###

# ActivateService
PATCH {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}/activate
Accept: {{json}}
Authorization: {{token}}

###

# DeactivateService
PATCH {{Sphera_API_HostAddress}}/api/v1/Services/{{uuid}}/deactivate
Accept: {{json}}
Authorization: {{token}}
